version: '3.6'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: caddy:2-alpine
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/x-wing/www/reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - /home/x-wing/www/reverse-proxy/data:/data
      - /home/x-wing/www/reverse-proxy/config:/config
      - /mnt/sdb/www/caddy/static:/var/www/static
