version: '3.6'
services:
  caddy:
    container_name: caddy
    image: abiosoft/caddy
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/x-wing/www/caddy/Caddyfile:/etc/Caddyfile
      - /home/x-wing/www/caddy/.caddy:/root/.caddy
      - /mnt/sdb/www/caddy/static:/var/www/static
    environment:
      - ACME_AGREE=true
